// Адрес демо стенда
url = "https://demoblaze.com"
reportsFolder = "target/test-result/reports"

// Настройки Selenide
browser = "chrome"
browserSize = "1920x1080"
headless = true
reportsFolder = "target/test-result/reports"
timeout = 15000

// авторизация на сайте
usersParams {
    testUser {
        login = "demoblaze"
        pass = "demoblaze"
    }
}